script/plugin-tdoc/md-to-wc.mjs
site/index.html
site/pages/layout/td-wc-content/index.tsx
tsconfig.build.json
tsconfig.json

fix(demo): html原生标签浏览器默认行为失效

---

package.json
site/vite.config.ts

fix(site): treeshake unpackaged css

---

.github/workflows/typos-config.toml

chore(spell-check): 移除对dom.ts文件的检查

---

src/tooltip/tooltip.tsx

fix(tooltip): 修复tolltip点击不出现问题

---

package-lock.json
package.json

fix(omi): isLightDom 重复渲染

---

src/avatar/README.md

docs(avatar): update avatar docs

---

.eslintrc.cjs
site/sidebar.config.ts
src/_util/dom.ts
src/_util/helper.ts
src/button/button.tsx
src/button/type.ts
src/dropdown/README.md
src/dropdown/_example/base.tsx
src/dropdown/_example/button.tsx
src/dropdown/_example/child.tsx
src/dropdown/_example/custom.tsx
src/dropdown/_example/disabled.tsx
src/dropdown/_example/icon.tsx
src/dropdown/_example/left.tsx
src/dropdown/_example/long.tsx
src/dropdown/_example/multiple.tsx
src/dropdown/_example/split.tsx
src/dropdown/_example/theme.tsx
src/dropdown/defaultProps.ts
src/dropdown/dropdown.tsx
src/dropdown/dropdownItem.tsx
src/dropdown/dropdownMenu.tsx
src/dropdown/getDropdownOptions.ts
src/dropdown/index.ts
src/dropdown/style/index.js
src/dropdown/type.ts
src/index.ts
src/message/index.tsx
src/popup/popup.tsx
src/popup/popupTrigger.tsx

feat(dropdown): dropdown complete 🎉

---

src/_util/lightDom.ts

- fix(util): fix convertToLightDom beforeRender

fix(util): fix lightDom beforeRender

---

site/sidebar.config.ts
src/badge/README.md
src/badge/_example/baseCustom.tsx
src/badge/_example/baseDotStyle.tsx
src/badge/_example/baseNumberStyle.tsx
src/badge/_example/baseOffset.tsx
src/badge/_example/baseShape.tsx
src/badge/_example/baseSize.tsx
src/badge/badge.tsx
src/badge/index.ts
src/badge/style/index.js
src/badge/type.ts
src/index.ts

[#122](https://github.com/TDesignOteam/tdesign-web-components/issues/122)
feat(badge): 添加 badge 组件

Feature/badge 增加badge组件

---

package-lock.json
package.json
src/_util/icon.ts
src/button/_example/icon.tsx
src/button/_example/shape.tsx
src/button/button.tsx
src/icon/README.md
src/tag/tag.tsx

- fix(icon): 修复icon不居中显示和class重复设置问题

fix(icon): 修复icon不居中显示和class重复设置问题

---

site/sidebar.config.ts
src/index.ts
src/swiper/README.md
src/swiper/_example/base.tsx
src/swiper/_example/card.tsx
src/swiper/_example/current.tsx
src/swiper/_example/fade.tsx
src/swiper/_example/fraction.tsx
src/swiper/_example/placement.tsx
src/swiper/_example/size.tsx
src/swiper/_example/vertical.tsx
src/swiper/index.ts
src/swiper/style/index.ts
src/swiper/swiper-item.tsx
src/swiper/swiper.tsx
src/swiper/type.ts

- ✅ 分支合并
#17 
- feat(swiper): 新增swiper组件

feat(swiper): add swiper component

---

package-lock.json
package.json
site/sidebar.config.ts
src/_util/linearGradient.ts
src/index.ts
src/progress/README.md
src/progress/_example/circle.tsx
src/progress/_example/line.tsx
src/progress/index.ts
src/progress/progress.tsx
src/progress/style/index.js
src/progress/type.ts

feat(progress): add new component progress

---

site/sidebar.config.ts
src/_util/noop.ts
src/index.ts
src/tabs/README.md
src/tabs/TabBar.tsx
src/tabs/TabNav.tsx
src/tabs/TabNavItem.tsx
src/tabs/_example/ban.tsx
src/tabs/_example/base.tsx
src/tabs/_example/position.tsx
src/tabs/_example/size.tsx
src/tabs/_example/theme.tsx
src/tabs/index.ts
src/tabs/style/index.js
src/tabs/tabPanel.tsx
src/tabs/tabs.tsx
src/tabs/type.ts
src/tabs/useTabClass.ts

Tabs compelete🎉
https://github.com/TDesignOteam/tdesign-web-components/issues/19
feat(tabs) : tabs compelete🎉

tabs compelete🎉

---

src/tag-input/_example/base.tsx
src/tag-input/_example/collapsed.tsx
src/tag-input/_example/custom-tag.tsx
src/tag-input/_example/excess.tsx
src/tag-input/tag-input.tsx
src/tag-input/type.ts

- 修复 中文拼音输入bug（输入中文拼音时， 按backspace会删除之前存在的 tag）
- 完成 https://github.com/TDesignOteam/tdesign-web-components/pull/114 中的代码风格优化
- fix(tag-input): 修复 中文拼音输入bug（输入中文拼音时， 按backspace会删除之前存在的 tag）

fix: tag-input

---

package-lock.json
package.json

fix(icon): 修复多次渲染问题

---

package-lock.json
package.json

- fix(input): 升级 omi fix input

fix(input): 升级 omi fix input

---

src/menu/MenuItem.tsx

fix(menu): fix 收起样式

---

.vscode/settings.json
package-lock.json
package.json
script/plugin-tdoc/md-to-wc.mjs
site/main.tsx
site/pages/layout/td-wc-content/index.tsx

fix(doc): doc类型README.md无法高亮显示代码块问题

---

package.json
site/sidebar.config.ts

feat(alpha): 发布alpha测试版本

---

README-zh_CN.md
README.md

feat(README): 更新版本信息

---

script/generate-entry.js
site/docs/getting-started.md
src/index.ts
src/menu/MenuItem.tsx
src/message/const.tsx
src/message/message.tsx
src/message/messageClose.tsx
src/message/messageComponent.tsx
src/message/messageIcon.tsx
src/range-input/RangeInput.tsx
src/range-input/RangeInputInner.tsx
src/range-input/type.ts
src/react.ts

feat(use): 支持在React环境中使用

---

script/rollup.config.js
site/docs/getting-started.md
site/docs/theme.md
site/sidebar.config.ts

docs(site): 官网文案优化

---

site/docs/getting-started.md
src/vue.ts

feat(Vue): 支持在Vue中使用

---

src/slider/_example/base.tsx
src/slider/_example/disabled.tsx
src/slider/_example/input-number-vertical.tsx
src/slider/_example/input-number.tsx
src/slider/_example/marks.tsx
src/slider/_example/min-and-max.tsx
src/slider/_example/step.tsx
src/slider/_example/vertical-marks.tsx
src/slider/_example/vertical.tsx

fix(slider): 修改展示问题

---

PUBLISH.md
README-zh_CN.md
README.md
package-lock.json
package.json
site/docs/getting-started.md
src/jsx.ts
src/react.ts
src/vue.ts

feat(jsx): 支持jsx通用方法

---

README-zh_CN.md
README.md
site/docs/getting-started.md
site/docs/react.md
site/docs/vue.md
site/sidebar.config.ts

chore(docs): 优化使用文档

---

package-lock.json
plugins/babel-plugin-add-part-attribute.cjs

fix(babel): 修复babel添加part插件失效问题

---

package-lock.json
package.json
plugins/babel-plugin-add-part-attribute.cjs
site/vite-plugin-add-part.js
site/vite.config.ts

* refactor(site): 官网和dev模式增加自动加part效果

refactor(site): 官网和dev模式增加自动加part效果 (#196)

---

src/collapse/collapse-panel.tsx

fix(collapse): 修复collapse动画不执行问题

---

package-lock.json
package.json
src/collapse/collapse-panel.tsx

fix(omi): 通过 css props 插入的 style 标签层级保持和 shadowroot 一致

---

package-lock.json
src/message/messageComponent.tsx
src/message/messageIcon.tsx
src/message/style/messageIcon.less

fix(message): 修复打包后引用message报错问题

---

CHANGELOG.md
package.json

feat: release 1.0.0

---

CHANGELOG.md
package.json

Update package.json 1.0.2

---

package.json

release 1.0.3 package.json

---

src/chat-message/chat-item.tsx
src/chat-message/style/chat-item.less
src/chatbot/_example/basic.tsx

feat(chatbot): attachment place on top

---

src/chat-message/style/chat-item.less
src/chatbot/style/_var.less

fix(chatMessage): fix markdown code overflow

---

src/chat-message/content/thinking-content.tsx

fix(thinking): 修复字段重名

---

src/chatbot/style/_var.less
src/skeleton/skeleton.tsx

fix(markdown): update markdown var / skeleton col part

---

src/chatbot/chat-list.tsx

修复chatList自动滚动功能，解决方案为调整上滚判断逻辑为：总高度未变更 && 滚动diff大于阈值

fix(chatbot-list): fix auto scroll

---

src/chat-message/content/markdown-content.tsx
src/chat-message/md/chat-md-code.tsx
src/chat-message/md/utils.ts
src/chatbot/_example/markdown.tsx

feat(markdown): markdown's dom append part attrs

---

package.json
src/chatbot/_example/basic.tsx

feat(chatbot): release 1.1.8

---

src/chat-message/chat-item.tsx
src/chat-message/content/attachment-content.tsx
src/chat-message/content/search-content.tsx
src/chat-message/content/suggestion-content.tsx
src/chat-message/content/thinking-content.tsx

fix(chatbot): fix item render content key

---

src/chatbot/chat-list.tsx
src/chatbot/style/_var.less
src/chatbot/style/chat-list.less

fix(chatlist): fix scroll button render

---

package-lock.json
src/chat-message/README.md
src/chat-message/_example/loading.tsx
src/chat-message/_example/style.tsx
src/chat-message/chat-item.tsx
src/chat-message/style/chat-item.less
src/chatbot/_example/customRenderItem.tsx
src/chatbot/style/_var.less

feat(chat-item): add content slot, adjust status effect conditions

---

package-lock.json
src/chat-message/_example/loading.tsx
src/chat-message/chat-item.tsx
src/chat-message/style/chat-item.less

fix(chat-item): fix style

---

package-lock.json
src/attachments/attachments.tsx
src/chat-message/chat-item.tsx
src/chat-message/content/attachment-content.tsx
src/chat-message/style/chat-item.less
src/chatbot/_example/customRenderItem.tsx
src/filecard/filecard.tsx

fix(attachments): fix onFileClick in vue

---

src/chat-message/style/chat-content.less

fix(cherrymd): link图标

---

src/chat-sender/chat-sender.tsx

 fix(sender): fix sender default value

---

src/chat-message/chat-item.tsx
src/chat-message/md/chat-md-code.tsx

fix(chat-item): fix code copy & fix chat-item message

---

src/chat-message/content/attachment-content.tsx
src/chat-message/style/chat-item.less

fix(chatItem): fix user right attachments
